apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: '{{ .Values.namespace }}'
  annotations:
    iam.gke.io/gcp-service-account: '{{ .Values.gcp_service_account_email }}'
  name: '{{ .Values.k8s_service_account_name }}'
