apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: '{{ .Values.namespace }}'
  name: '{{ .Values.project_id }}-publisher-deployment-{{ .Values.region }}'
  labels:
    app: publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
    spec:
      serviceAccountName: '{{ .Values.k8s_service_account_name }}'
      containers:
        - env:
          - name: EVENT_TOPIC
            valueFrom:
              configMapKeyRef:
                key: EVENT_TOPIC
                name: '{{ .Values.project_id }}-publisher-config-maps-{{ .Values.region }}'
          - name: PUBLISHER_THREADS
            valueFrom:
              configMapKeyRef:
                key: PUBLISHER_THREADS
                name: '{{ .Values.project_id }}-publisher-config-maps-{{ .Values.region }}'
          - name: PUBLISHER_FLOW_CONTROL_MAX_OUTSTANDING_MESSAGES
            valueFrom:
              configMapKeyRef:
                key: PUBLISHER_FLOW_CONTROL_MAX_OUTSTANDING_MESSAGES
                name: '{{ .Values.project_id }}-publisher-config-maps-{{ .Values.region }}'
          - name: REST_PORT
            valueFrom:
              configMapKeyRef:
                key: REST_PORT
                name: '{{ .Values.project_id }}-publisher-config-maps-{{ .Values.region }}'
          - name: GOOGLE_CLOUD_LOCATION
            value: '{{ .Values.region }}'
          name: '{{ .Values.project_id }}-publisher-{{ .Values.region }}'
          image: '{{ .Values.image }}'
          resources:
            requests:
              cpu: "1000m"
